// Copyright 2020 GHA Test Team
#ifndef INCLUDE_GITHUB_ACTIONS_GTEST_EXAMPLE_GITHUB_ACTIONS_GTEST_EXAMPLE_H_
#define INCLUDE_GITHUB_ACTIONS_GTEST_EXAMPLE_GITHUB_ACTIONS_GTEST_EXAMPLE_H_

#include <iostream>
#include <string>


std::string sayHello();
int add(int _first, int _second);

#endif  // INCLUDE_GITHUB_ACTIONS_GTEST_EXAMPLE_GITHUB_ACTIONS_GTEST_EXAMPLE_H_
